### ISSUE TITLE
Include the agent version and other relevant information in each agent message

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#100]
## Description

This issue involves including the agent version in every message the agent sends to the manager. Additionally, it may also be useful to include other information, such as the UUID, in every agent message.

###Tasks:

- [ ] Evaluate what information is useful to include in every agent message.
  - The information should never change or should not change frequently (at least not before a restart).
- [ ] Include the information in the header of every message in `user-agent`.
  - The UUID can be sent in a different field.
- [ ] If useful, also include the relevant information in the authentication request so that it is also encoded in the token.

**Comment by Dwordcito** [comment]
Does this field come in a stateless payload with a 5.0.0 protocol?

**Comment by TomasTurina** [comment]
Already implemented.
