### ISSUE TITLE
Migrate the `Packages_builder_solaris` and  `Packages_builder_special` pipeline to GHA

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-agent#121]
| Objective |
|---|
| https://github.com/wazuh/wazuh-packages/issues/2904 | 

## Description
Because of the `Wazuh packages redesign tier 2` objective we need to migrate the `Packages_builder_solaris` and 
`Packages_builder_special` pipeline to a GHA.

## Tasks
- [ ] Replicate the `Packages_builder_solaris`  from the Jenkins pipeline to GHA.
- [ ] Replicate the `Packages_builder_special`  from the Jenkins pipeline to GHA.
- [ ] Test the pipeline migrated and provide evidence.
