### ISSUE TITLE
Create Installation Packages for Wazuh Agent

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-agent#128]
**Parent Issue:**
- https://github.com/wazuh/wazuh-agent/issues/126

## Description

This issue focuses on creating platform-specific packages (RPM, DEB, MSI, PKG) to facilitate the installation of the Wazuh agent across supported operating systems. The packages should integrate with the native package managers and follow best practices for each platform.

## Functional Requirements

- **Linux**: Create RPM and DEB packages to install the Wazuh agent on RHEL-based and Debian-based distributions.
- **Windows**: Create an MSI installer for the Wazuh agent.
- **macOS**: Create a PKG installer for macOS 14+.

## Subtasks

- [x] https://github.com/wazuh/wazuh-agent/issues/133
   - Develop an RPM spec file for RHEL, CentOS, Fedora, and similar distributions.
- [x] https://github.com/wazuh/wazuh-agent/issues/143
   - Create a DEB package for Debian-based distributions (Ubuntu, Debian, etc.).
- [x] https://github.com/wazuh/wazuh-agent/issues/134
   - Develop an MSI installer for Windows.
   - Ensure the installer correctly registers the agent as a Windows Service.
   - Handle dependencies and any required installation scripts (pre/post-install).
- [x] https://github.com/wazuh/wazuh-agent/issues/135
   - Develop a PKG installer for macOS.
   - Ensure the installer sets up the agent as a launch daemon.
   - Handle installation-related tasks like setting up permissions and configuring files.
- [x] **Documentation:**
   - Create installation instructions for each type of package (RPM, DEB, MSI, PKG).
   - Provide troubleshooting guidelines for package-related issues.

**Comment by mjcr99** [comment]
## Update
**(16/10/2024)** Added option to run `make install` and let every built file in the desired folder based on the building environment. We are waiting for this development to complete the service installation:
* https://github.com/wazuh/wazuh-agent/pull/221

**Comment by lchico** [comment]
# Update
- I have been working on the following issues:

```bash
[ 98%] Building CXX object CMakeFiles/wazuh-agent.dir/agent/src/main.cpp.o
[100%] Linking CXX executable wazuh-agent
`_ZN5boost4asio6detail20co_spawn_entry_pointEPZNS1_20co_spawn_entry_pointINS1_16detached_handlerENS0_15any_io_executorENS1_21awaitable_as_functionIvS4_EEEENS0_9awaitableINS1_28awaitable_thread_entry_pointET0_EEPNS7_IvS9_EENS1_14co_spawn_stateIT_S9_T1_vEEE230_ZN5boost4asio6detail20co_spawn_entry_pointINS1_16detached_handlerENS0_15any_io_executorENS1_21awaitable_as_functionIvS4_EEEENS0_9awaitableINS1_28awaitable_thread_entry_pointET0_EEPNS7_IvS9_EENS1_14co_spawn_stateIT_S9_T1_vEE.Frame.destroy' referenced in section `.rodata.cst8' of modules/logcollector/libLogcollector.a(logcollector.cpp.o): defined in discarded section `.text._ZN5boost4asio6detail20co_spawn_entry_pointEPZNS1_20co_spawn_entry_pointINS1_16detached_handlerENS0_15any_io_executorENS1_21awaitable_as_functionIvS4_EEEENS0_9awaitableINS1_28awaitable_thread_entry_pointET0_EEPNS7_IvS9_EENS1_14co_spawn_stateIT_S9_T1_vEEE230_ZN5boost4asio6detail20co_spawn_entry_pointINS1_16detached_handlerENS0_15any_io_executorENS1_21awaitable_as_functionIvS4_EEEENS0_9awaitableINS1_28awaitable_thread_entry_pointET0_EEPNS7_IvS9_EENS1_14co_spawn_stateIT_S9_T1_vEE.Frame.destroy[_ZN5boost4asio6detail20co_spawn_entry_pointINS1_16detached_handlerENS0_15any_io_executorENS1_21awaitable_as_functionIvS4_EEEENS0_9awaitableINS1_28awaitable_thread_entry_pointET0_EEPNS7_IvS9_EENS1_14co_spawn_stateIT_S9_T1_vEE]' of modules/logcollector/libLogcollector.a(logcollector.cpp.o)
collect2: error: ld returned 1 exit status
make[2]: *** [wazuh-agent] Error 1
make[1]: *** [CMakeFiles/wazuh-agent.dir/all] Error 2
make: *** [all] Error 2
error: Bad exit status from /usr/local/var/tmp/rpm-tmp.xd9Atp (%build)

RPM build errors:
    Bad exit status from /usr/local/var/tmp/rpm-tmp.xd9Atp (%build)
```
This error occurs when we try to generate an RPM package by running the following command on the master branch:

```
./packages/generate_package.sh --system rpm -t agent --tag 5.0.0
```

We have identified that if we build using the "Debug" mode instead of "Release," this issue does not occur:

```
cmake . -B build -DCMAKE_BUILD_TYPE=Debug
cmake --build build -j 16
```
