### ISSUE TITLE
Replace `os_net` with a Standard Library in the Agent

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#155]
**Parent issue:**
- [Migrate Syscollector module to new agent](https://github.com/wazuh/wazuh-agent/issues/17)

## Description
Deprecate or remove the **os_net** library and replace it with a standard alternative (to be determined). This will ensure compatibility and long-term maintainability of the project.

## Tasks
- [ ] Investigate and propose a suitable replacement for `os_net`.
- [ ] Identify where `os_net` is used in the codebase.
- [ ] Replace `os_net` with the selected library.
- [ ] Refactor the code for compatibility.

## Testing tasks
- [ ] Create or modify unit tests for the new implementation.
- [ ] Test the solution on all supported platforms.

**Comment by cborla** [comment]
This issue was defined for 6.0 according to the dependencies used by inventory, which is not necessary. The library was replaced by generic modules.
