### ISSUE TITLE
Enhancing Wazuh Agent Pipeline with Module-Specific Smoke Tests

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh-agent#166]
## Related Issues

- https://github.com/wazuh/wazuh-agent/issues/66

## Description

This issue proposes the final step to fully implement the pipeline for running smoke tests with specific modules. To achieve this, we need to define the list of modules to check whether they are active.

We also need to create an API command that interacts with each module and specifies the expected response to confirm its functionality.

## Tasks

- [ ] List the agent modules for which we want to request the status.
- [ ]  Create an API request for each module.
- [ ]  Ensure the API response validates that the modules are working as expected.
- [ ]  Update the workflow implemented in this [issue](https://github.com/wazuh/wazuh-agent/issues/66) with these checks.

## Acceptance Criteria
Select one or more modules and verify that they return the expected response under normal conditions. In the case of failure, the system should detect it.

**Comment by lchico** [comment]
# Update
- I just started working on this, reviewing the task and looking at https://github.com/wazuh/wazuh-agent/issues/66.
- I will define the ETA for this task tomorrow.
