### ISSUE TITLE
Support new stage Alpha 1 for 4.10.0 in wazuh-agent repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-agent#168]
## Description

This issue attempts to support a new stage Alpha 1 for 4.10.0 in the wazuh-agent repository.

## Tasks

- [ ] Ensure changelog is updated for 4.10.0 (if applicable).
- [ ] Bump revision for branch 4.10.0 on wazuh-agent repository.
- [ ] Create tag v4.10.0-alpha1 from branch 4.10.0 on wazuh-agent repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-agent/releases/tag/v4.10.0-alpha1.
