### ISSUE TITLE
Integrate external dependencies as vcpkg managed dependencies and remove vcpkg from submodule

### ISSUE THREAD

**Issue by mjcr99** [wazuh/wazuh-agent#173]
### Related Issues

- **Parent:** https://github.com/wazuh/wazuh-agent/issues/65

## Description

After the development carried on here https://github.com/wazuh/wazuh-agent/issues/65, many OS dependencies related to `librpm` are being added as seen in this workflow: 

https://github.com/wazuh/wazuh-agent/blob/56a3571dc27119147a1d227d78cbba1367d6384a/.github/workflows/build_and_test_component.yml#L25-L32

This can be avoided by letting vcpkg manage these dependencies, this way the amount of external dependencies managed by the OS will be reduced.

In addition, we are going to adapt the build to be able to remove the vcpkg code as a submodule, as this recommendation was deprecated and there are other ways to adapt the project to avoid having vcpkg as a submodule.
> - https://learn.microsoft.com/en-gb/vcpkg/get_started/get-started?pivots=shell-bash
> - https://learn.microsoft.com/en-gb/vcpkg/users/buildsystems/cmake-integration

## Tasks

- [ ] **Research to integrate as many external dependencies as possible into `vcpkg`. And adapt `vcpkg` to the project, avoiding it as a submodule**:
  - Try to reduce as much as possible the external dependencies needed.
  - Find the best way to adapt `vcpkg` to the project, avoiding it as a submodule.
- [ ] **Modify the workflows and actions necessary to implement the new adaptation. And adapt the build code for `vcpkg`**:
  - Modify the compilation with the new method to avoid `vcpkg` as a submodule.
  - Test it with GHA and locally.
- [ ] **Ensure that the pipeline supports all required platforms**:
    - Platforms: Windows, Linux, and macOS.
- [ ] **Documentation**:
    - Document the necessary steps to follow this procedure (update BUILD.md, and if other documentation exists, update it as well).

**Comment by cborla** [comment]
Note that some OSes already have `libbz2-dev` and others do not, being required for `librpm`.

**Comment by mjcr99** [comment]
Achieved with:
* https://github.com/wazuh/wazuh-agent/issues/544
* https://github.com/wazuh/wazuh-agent/issues/542
