### ISSUE TITLE
Improve Inventory Implementation

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#193]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0 | Wazuh agent | Agent | Packages/Sources | MacOS|

# Improve Inventory Implementation

This Issue addresses multiple tasks related to the macOS and Windows agent implementation. Below is a summary of the task:

## Tasks

- [x] Fix failing `data provider` tests on macOS.
- [x] Analyze the feasibility of removing or replacing `BSDBASED`.
- [x] Adjust the README, specifically the section on "3rd Party Software Used".
- [x] Perform tests with mock server and macOS agent.
- [x] Changed dlls output directory at windows compilation.

## Context

For analyzing the feasibility of removing or replacing `BSDBASED`, the current implementation includes an enum for `OSPlatformType`:

```cpp
enum OSPlatformType
{
    LINUX,
    BSDBASED,
    WINDOWS,
};
```
## Definition of Done
- All `data provider` tests pass successfully on macOS without any intermittent failures.
- A decision is made on whether to remove or replace `BSDBASED`:
  - If removed or replaced, the changes are documented, and the code is refactored accordingly.
  - If kept, justification and documentation are updated to reflect why it remains necessary.
- The README file is updated, specifically:
  - The "3rd Party Software Used" section is reviewed and contains accurate and up-to-date information.
- Mock server tests with the macOS agent are performed, and all functionalities work as expected:
  - No unexpected behavior or performance issues are identified during testing.
- All relevant documentation is updated to reflect changes made during this process.

**Comment by nbertoldo** [comment]
### Update 2024/10/02

Set up the [server-mock](https://github.com/wazuh/wazuh-agent/tree/test/25-server-mock) and tried to register the new agent, but the server is not up to date, so they are not compatible.
Then the deployment was made using the following docker files:
https://github.com/wazuh/wazuh-tools/tree/test/24305-comms-api-env/framework/environments/dev
The master node give this error:
```console
Starting Wazuh v5.0.0...
wazuh-comms-apid did not start correctly.
```

There is already an isssue about this: [Investigate and fix the error related to the batcher](https://github.com/wazuh/wazuh/issues/26086#top)

**Comment by nbertoldo** [comment]
## Test Inventory on macOS Sonoma X86

The _agent_ is started and verified that the _inventory_ module launches a scan generating the expected _stateless_ and _stateful_ events.
Then the queue database is queried to verify that the events have been inserted correctly. 

### Configuration

```toml
[agent]
server_mgmt_api_port = "55000"
agent_comms_api_port = "27000"
manager_ip = "localhost"
https_enabled = "yes"

[inventory]
enabled = true
interval = 3600
scan_on_start = true
hardware = true
os = true
network = true
packages = true
ports = true
ports_all = true
processes = true
hotfixes = true
```

### Logs

```log
Timestamp                       Thread     Type        Activity             PID    TTL
2024-10-03 14:26:20.023630-0700 0x43482    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:20.048] [wazuh-agent] [info] [INFO] [main.cpp:13] [main] Starting Wazuh Agent.
2024-10-03 14:26:20.071550-0700 0x43486    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:20.096] [wazuh-agent] [info] [INFO] [inventory.cpp:19] [Start] Starting inventory.
2024-10-03 14:26:20.076000-0700 0x43486    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:20.101] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:787] [SyncLoop] Module started.
2024-10-03 14:26:20.076031-0700 0x43486    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:20.101] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:771] [Scan] Starting evaluation.
2024-10-03 14:26:20.847744-0700 0x43486    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:20.872] [wazuh-agent] [info] [INFO] [inventoryImp.cpp:782] [Scan] Evaluation finished.
2024-10-03 14:26:28.246354-0700 0x43482    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:28.271] [wazuh-agent] [info] [INFO] [inventory.cpp:58] [Stop] Module stopped.
2024-10-03 14:26:28.247347-0700 0x43486    Info        0x0                  88392  0    wazuh-agent: [2024-10-03 14:26:28.272] [wazuh-agent] [info] [INFO] [inventory.cpp:38] [Start] Module finished.

```

### Queue database

<details><summary>Stateful events</summary>

```console

sqlite> select * from STATEFUL LIMIT 10;
module     message                                                     
---------  ------------------------------------------------------------
inventory  {"data":{"board_serial":"H2WF603JPJJ9","checksum":"c8afb5537
           fc494d27361efd0ac11b9b6e725965c","cpu_cores":2,"cpu_mhz":319
           2.0,"cpu_name":"Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz","r
           am_free":800332,"ram_total":4194304,"ram_usage":81,"scan_tim
           e":"2024/10/03 21:26:20"},"operation":"INSERTED","type":"dbs
           ync_hwinfo"}                                                

inventory  {"data":{"architecture":"x86_64","checksum":"172799078052565
           3","hostname":"macos-1460","os_build":"23G93","os_codename":
           "Sonoma","os_major":"14","os_minor":"6","os_name":"macOS","o
           s_patch":"1","os_platform":"darwin","os_version":"14.6.1","r
           elease":"23.6.0","scan_time":"2024/10/03 21:26:20","sysname"
           :"Darwin","version":"Darwin Kernel Version 23.6.0: Mon Jul 2
           9 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64"}
           ,"operation":"INSERTED","type":"dbsync_osinfo"}             

inventory  {"data":{"adapter":null,"checksum":"0772f4641f96c6bebb9353a8
           bcd6670537a9199b","item_id":"9fb848961bda780128fd2ee8c870bdf
           1b481d94c","mac":"00:1c:42:ea:04:7d","mtu":1500,"name":"en0"
           ,"rx_bytes":1418361856,"rx_dropped":0,"rx_errors":0,"rx_pack
           ets":982859,"scan_time":"2024/10/03 21:26:20","state":"up","
           tx_bytes":9802752,"tx_dropped":0,"tx_errors":0,"tx_packets":
           90228,"type":"ethernet"},"operation":"INSERTED","type":"dbsy
           nc_network_iface"}                                          

inventory  {"data":{"adapter":null,"checksum":"751c7b530713583d8d68eb6f
           1af0137bb071651f","item_id":"d3f22d992b65724e5c061fd5023609a
           c4a3d5963","mac":"00:00:00:00:00:00","mtu":1280,"name":"gif0
           ","rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_packets":0,"
           scan_time":"2024/10/03 21:26:20","state":"down","tx_bytes":0
           ,"tx_dropped":0,"tx_errors":0,"tx_packets":0,"type":" "},"op
           eration":"INSERTED","type":"dbsync_network_iface"}          

inventory  {"data":{"adapter":null,"checksum":"d3b18b8dd6fa2f21cb3a076a
           24cad7f2dd94387b","item_id":"db148c7716f8cc0fc3f6521932d74e6
           a825ef292","mac":"00:00:00:00:00:00","mtu":1280,"name":"stf0
           ","rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_packets":0,"
           scan_time":"2024/10/03 21:26:20","state":"down","tx_bytes":0
           ,"tx_dropped":0,"tx_errors":0,"tx_packets":0,"type":" "},"op
           eration":"INSERTED","type":"dbsync_network_iface"}          

inventory  {"data":{"checksum":"075d9e097822667b9a4e15d098ce9c8878ce281
           b","dhcp":"unknown","gateway":"10.211.55.1","iface":"en0","i
           tem_id":"801d5dedbeebfbb9d66394994ffc3a6765164cd9","metric":
           null,"scan_time":"2024/10/03 21:26:20","type":"ipv4"},"opera
           tion":"INSERTED","type":"dbsync_network_protocol"}          

inventory  {"data":{"checksum":"fce59e7b664e2938552a59926d6c03a2a799c77
           6","dhcp":"unknown","gateway":"10.211.55.1","iface":"en0","i
           tem_id":"a63b929cbff14039ff7a98cec1981e4d51b68c6a","metric":
           null,"scan_time":"2024/10/03 21:26:20","type":"ipv6"},"opera
           tion":"INSERTED","type":"dbsync_network_protocol"}          

inventory  {"data":{"address":"10.211.55.47","broadcast":"10.211.55.255
           ","checksum":"0f3723ca04a1685f13f53274a5ed01f6f3fc31b0","ifa
           ce":"en0","item_id":"e77f0807efc486998153264865c562b4667826b
           6","netmask":"255.255.255.0","proto":0,"scan_time":"2024/10/
           03 21:26:20"},"operation":"INSERTED","type":"dbsync_network_
           address"}                                                   

inventory  {"data":{"address":"fe80::1cee:5dcb:5f59:443","broadcast":nu
           ll,"checksum":"ca339af1172507aebd4ffc41d8b245bbbeebb2d4","if
           ace":"en0","item_id":"e39c4916e97c618c2fd50fbac8a6bae4ad7e99
           19","netmask":"ffff:ffff:ffff:ffff::","proto":1,"scan_time":
           "2024/10/03 21:26:20"},"operation":"INSERTED","type":"dbsync
           _network_address"}                                          

inventory  {"data":{"address":"fdb2:2c26:f4e4:0:ee:d9f1:fbf6:e9c7","bro
           adcast":null,"checksum":"0ab6c869ad85cea79dd57865e4176d00008
           6fea6","iface":"en0","item_id":"fbdd187b3678b09e8c4de3bb0353
           6bfdd5d39fe8","netmask":"ffff:ffff:ffff:ffff::","proto":1,"s
           can_time":"2024/10/03 21:26:20"},"operation":"INSERTED","typ
           e":"dbsync_network_address"}  

```

</details> 


<details><summary>Stateless events</summary>

```console

sqlite> select * from STATELESS LIMIT 10;
module     message                                                     
---------  ------------------------------------------------------------
inventory  {"data":{"board_serial":"H2WF603JPJJ9","checksum":"c8afb5537
           fc494d27361efd0ac11b9b6e725965c","cpu_cores":2,"cpu_mhz":319
           2.0,"cpu_name":"Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz","r
           am_free":800332,"ram_total":4194304,"ram_usage":81,"scan_tim
           e":"2024/10/03 21:26:20"},"operation":"INSERTED","type":"dbs
           ync_hwinfo"}                                                

inventory  {"data":{"architecture":"x86_64","checksum":"172799078052565
           3","hostname":"macos-1460","os_build":"23G93","os_codename":
           "Sonoma","os_major":"14","os_minor":"6","os_name":"macOS","o
           s_patch":"1","os_platform":"darwin","os_version":"14.6.1","r
           elease":"23.6.0","scan_time":"2024/10/03 21:26:20","sysname"
           :"Darwin","version":"Darwin Kernel Version 23.6.0: Mon Jul 2
           9 21:13:00 PDT 2024; root:xnu-10063.141.2~1/RELEASE_X86_64"}
           ,"operation":"INSERTED","type":"dbsync_osinfo"}             

inventory  {"data":{"adapter":null,"checksum":"0772f4641f96c6bebb9353a8
           bcd6670537a9199b","item_id":"9fb848961bda780128fd2ee8c870bdf
           1b481d94c","mac":"00:1c:42:ea:04:7d","mtu":1500,"name":"en0"
           ,"rx_bytes":1418361856,"rx_dropped":0,"rx_errors":0,"rx_pack
           ets":982859,"scan_time":"2024/10/03 21:26:20","state":"up","
           tx_bytes":9802752,"tx_dropped":0,"tx_errors":0,"tx_packets":
           90228,"type":"ethernet"},"operation":"INSERTED","type":"dbsy
           nc_network_iface"}                                          

inventory  {"data":{"adapter":null,"checksum":"751c7b530713583d8d68eb6f
           1af0137bb071651f","item_id":"d3f22d992b65724e5c061fd5023609a
           c4a3d5963","mac":"00:00:00:00:00:00","mtu":1280,"name":"gif0
           ","rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_packets":0,"
           scan_time":"2024/10/03 21:26:20","state":"down","tx_bytes":0
           ,"tx_dropped":0,"tx_errors":0,"tx_packets":0,"type":" "},"op
           eration":"INSERTED","type":"dbsync_network_iface"}          

inventory  {"data":{"adapter":null,"checksum":"d3b18b8dd6fa2f21cb3a076a
           24cad7f2dd94387b","item_id":"db148c7716f8cc0fc3f6521932d74e6
           a825ef292","mac":"00:00:00:00:00:00","mtu":1280,"name":"stf0
           ","rx_bytes":0,"rx_dropped":0,"rx_errors":0,"rx_packets":0,"
           scan_time":"2024/10/03 21:26:20","state":"down","tx_bytes":0
           ,"tx_dropped":0,"tx_errors":0,"tx_packets":0,"type":" "},"op
           eration":"INSERTED","type":"dbsync_network_iface"}          

inventory  {"data":{"checksum":"075d9e097822667b9a4e15d098ce9c8878ce281
           b","dhcp":"unknown","gateway":"10.211.55.1","iface":"en0","i
           tem_id":"801d5dedbeebfbb9d66394994ffc3a6765164cd9","metric":
           null,"scan_time":"2024/10/03 21:26:20","type":"ipv4"},"opera
           tion":"INSERTED","type":"dbsync_network_protocol"}          

inventory  {"data":{"checksum":"fce59e7b664e2938552a59926d6c03a2a799c77
           6","dhcp":"unknown","gateway":"10.211.55.1","iface":"en0","i
           tem_id":"a63b929cbff14039ff7a98cec1981e4d51b68c6a","metric":
           null,"scan_time":"2024/10/03 21:26:20","type":"ipv6"},"opera
           tion":"INSERTED","type":"dbsync_network_protocol"}          

inventory  {"data":{"address":"10.211.55.47","broadcast":"10.211.55.255
           ","checksum":"0f3723ca04a1685f13f53274a5ed01f6f3fc31b0","ifa
           ce":"en0","item_id":"e77f0807efc486998153264865c562b4667826b
           6","netmask":"255.255.255.0","proto":0,"scan_time":"2024/10/
           03 21:26:20"},"operation":"INSERTED","type":"dbsync_network_
           address"}                                                   

inventory  {"data":{"address":"fe80::1cee:5dcb:5f59:443","broadcast":nu
           ll,"checksum":"ca339af1172507aebd4ffc41d8b245bbbeebb2d4","if
           ace":"en0","item_id":"e39c4916e97c618c2fd50fbac8a6bae4ad7e99
           19","netmask":"ffff:ffff:ffff:ffff::","proto":1,"scan_time":
           "2024/10/03 21:26:20"},"operation":"INSERTED","type":"dbsync
           _network_address"}                                          

inventory  {"data":{"address":"fdb2:2c26:f4e4:0:ee:d9f1:fbf6:e9c7","bro
           adcast":null,"checksum":"0ab6c869ad85cea79dd57865e4176d00008
           6fea6","iface":"en0","item_id":"fbdd187b3678b09e8c4de3bb0353
           6bfdd5d39fe8","netmask":"ffff:ffff:ffff:ffff::","proto":1,"s
           can_time":"2024/10/03 21:26:20"},"operation":"INSERTED","typ
           e":"dbsync_network_address"}   

```

</details>

**Comment by nbertoldo** [comment]
### Update 2024/10/04

Fix failing _data-provider_ (_SysInfo_) tests on _macOS_:

```console
vagrant@macos-1460 wazuh-agent % ctest --test-dir build --output-log build                                   
Internal ctest changing into directory: /Users/vagrant/wazuh-agent/build
Test project /Users/vagrant/wazuh-agent/build
      Start  1: sysInfoHardwareMac_unit_test
 1/31 Test  #1: sysInfoHardwareMac_unit_test ......   Passed    0.01 sec
      Start  2: sysInfoNetworkBSD_unit_test
 2/31 Test  #2: sysInfoNetworkBSD_unit_test .......   Passed    0.01 sec
      Start  3: sysInfoMacPackage_unit_test
 3/31 Test  #3: sysInfoMacPackage_unit_test .......   Passed    0.01 sec
      Start  4: sysInfoPackages_unit_test
 4/31 Test  #4: sysInfoPackages_unit_test .........   Passed    0.01 sec
      Start  5: sysinfo_unit_test
 5/31 Test  #5: sysinfo_unit_test .................   Passed    0.32 sec
      Start  6: sysInfoPort_unit_test
 6/31 Test  #6: sysInfoPort_unit_test .............   Passed    0.01 sec
      Start  7: sqlite_unit_test
 7/31 Test  #7: sqlite_unit_test ..................   Passed    0.02 sec
      Start  8: dbsync_unit_test
 8/31 Test  #8: dbsync_unit_test ..................   Passed    0.15 sec
      Start  9: dbsyncPipelineFactory_unit_test
 9/31 Test  #9: dbsyncPipelineFactory_unit_test ...   Passed    0.02 sec
      Start 10: dbengine_unit_test
10/31 Test #10: dbengine_unit_test ................   Passed    0.01 sec
      Start 11: fim_integration_test
11/31 Test #11: fim_integration_test ..............   Passed    0.59 sec
      Start 12: LoggerTest
12/31 Test #12: LoggerTest ........................   Passed    0.01 sec
      Start 13: InventoryImpTest
13/31 Test #13: InventoryImpTest ..................   Passed   32.69 sec
      Start 14: InvNormalizerTest
14/31 Test #14: InvNormalizerTest .................   Passed    0.32 sec
      Start 15: ModuleManagerTest
15/31 Test #15: ModuleManagerTest .................   Passed    0.40 sec
      Start 16: AgentInfoTest
16/31 Test #16: AgentInfoTest .....................   Passed    0.04 sec
      Start 17: AgentInfoPersistanceTest
17/31 Test #17: AgentInfoPersistanceTest ..........   Passed    0.03 sec
      Start 18: CommandHandlerTest
18/31 Test #18: CommandHandlerTest ................   Passed    0.01 sec
      Start 19: CommunicatorTest
19/31 Test #19: CommunicatorTest ..................   Passed    1.02 sec
      Start 20: HttpClientTest
20/31 Test #20: HttpClientTest ....................   Passed    3.02 sec
      Start 21: ConfigParserTest
21/31 Test #21: ConfigParserTest ..................   Passed    0.01 sec
      Start 22: MultiTypeQueueTest
22/31 Test #22: MultiTypeQueueTest ................   Passed    7.30 sec
      Start 23: SqliteStorageTest
23/31 Test #23: SqliteStorageTest .................   Passed    0.14 sec
      Start 24: SQLiteManager_test
24/31 Test #24: SQLiteManager_test ................   Passed    0.04 sec
      Start 25: CommandStoreTest
25/31 Test #25: CommandStoreTest ..................   Passed    0.02 sec
      Start 26: AgentTest
26/31 Test #26: AgentTest .........................   Passed    1.54 sec
      Start 27: TaskManagerTest
27/31 Test #27: TaskManagerTest ...................   Passed    0.51 sec
      Start 28: RegisterTest
28/31 Test #28: RegisterTest ......................   Passed    0.35 sec
      Start 29: SignalHandlerTest
29/31 Test #29: SignalHandlerTest .................   Passed    0.31 sec
      Start 30: MessageQueueUtilsTest
30/31 Test #30: MessageQueueUtilsTest .............   Passed    0.39 sec
      Start 31: CommandlineParserTest
31/31 Test #31: CommandlineParserTest .............   Passed    0.01 sec

100% tests passed, 0 tests failed out of 31

Total Test time (real) =  49.34 sec


```

**Comment by nbertoldo** [comment]
### Analyze the feasibility of removing or replacing 'BSDBASED'

After analyzing it, I consider removing the `BSDBASED` code unnecessary since it belongs to _Darwin (macOS)_. _Darwin_ incorporates many _BSD_ features, especially its network stack, file subsystem, and other utilities. 
In the particular case of the _data-provider_ the enum `OSPlatformType`:

```C
enum OSPlatformType
{
    LINUX,
    BSDBASED,
    WINDOWS,
};
```

Is used to differentiate the creation of objects according to the operating system on which it is running and to obtain information about hardware, networks, and packages.
