### ISSUE TITLE
Implement Selective Compilation of Optional Modules

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#207]
## **Description**

Currently the components are crucial for the application's functionality, while the modules are libraries that extend functionality by utilizing the essential components.

The goal of this issue is to implement **selective compilation** that allows including or excluding optional modules during the build process, using **CMake** to manage this configuration efficiently.

---

## **Motivation**

- **Flexibility:** Allow users to customize the application based on their needs by including only the required modules.
- **Optimization:** Reduce the final size of the application by excluding unnecessary modules.
- **Maintenance:** Facilitate the management and updating of optional modules without affecting the core application.

## **Proposed Solution**
The default behaviour is to always compile including all modules, and in case you want to exclude the compilation of one of them you can do it by command line or by disabling the internal define in cmake.
```bash
cmake -DUSE_FIM=OFF -DUSE_INVENTORY=OFF ..
```

## **Tasks**
1. Update CMakeLists.txt:
     - [x] Implement conditional options for modules.
     - [x] Configure dependencies between components and modules appropriately.
2. Modify Source Code:
    - [x] Add preprocessor macros where necessary to manage module-specific code inclusion, the idea is to only include the safeguards at one point, preferably in the `modules manager`.
3. Testing:
    - [x] Verify builds with different combinations of modules enabled and disabled.
    - [x] Ensure the application functions correctly in all configurations.
4. Documentation:
    - [ ] Update project documentation to reflect the new build options.
    - [ ] Include instructions on how to disable modules during the build process, include options in the `BUILD.md` file.

**Comment by nbertoldo** [comment]
### Update 2024/10/08

- Implement conditional options for modules:

```Cmake
option(ENABLE_MODULE_INVENTORY "Enable module Inventory" OFF)

if(ENABLE_MODULE_INVENTORY)
    message(STATUS "Module Inventory is enabled")
    add_definitions(-DENABLE_MODULE_INVENTORY)
    add_subdirectory(inventory)
else()
    message(STATUS "Module Inventory is disabled")
endif()
```

**Comment by nbertoldo** [comment]
### Update 2024/10/09

- Refactoring _ModuleManager_ to allow selective module building.

**Comment by nbertoldo** [comment]
### Update 2024/10/14

- Integrate _taskManager_ to _ModuleManager_.
- Suggested changes.

**Comment by nbertoldo** [comment]
### Update 2024/10/15

- Refactor _ModuleManager_.
- Rebase to _master_.
- Update _moduleManager_ unit tests.

**Comment by nbertoldo** [comment]
### Update 2024/10/15

- Setting up _Windows_ environment.
- Fixing unit test for _Windows_.

**Comment by nbertoldo** [comment]
### Update 2024/10/17

- Fix unit test for _Windows_: missing `dbsync` and `sysinfo` _.dlls_.

**Comment by cborla** [comment]
Moved to on hold until the release testing stage is completed.

**Comment by nbertoldo** [comment]
### Update 2024/10/23

- Rebase to _master_.
- Adapting _logcollector_ and _centralized_configuration_ to selective compilation.

**Comment by nbertoldo** [comment]
### Update 2024/10/24

- Adapting _logcollector_ to selective compilation.
- Fix tests
