### ISSUE TITLE
MVP Agent refinement (I)

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-agent#241]
# Description

We want to iterate and polish the MVP agent so we can test the overall design of the solution.

Currently, we have identified the following improvements: 

### October 25, 2024

- [x] https://github.com/wazuh/wazuh-agent/issues/242
- [x] https://github.com/wazuh/wazuh-agent/issues/243
- [x] https://github.com/wazuh/wazuh-agent/issues/244
- [x] https://github.com/wazuh/wazuh-agent/issues/245
- [x] https://github.com/wazuh/wazuh-agent/issues/246
- [x] https://github.com/wazuh/wazuh-agent/issues/251
- [x] https://github.com/wazuh/wazuh-agent/issues/253

### October 28, 2024

- [x] https://github.com/wazuh/wazuh-agent/issues/255
- [x] https://github.com/wazuh/wazuh-agent/issues/256
- [x] https://github.com/wazuh/wazuh-agent/issues/260

### October 31, 2024

- [x] #103

### November 5, 2024

- [x] https://github.com/wazuh/wazuh-agent/issues/275

### November 8, 2024

- [x] #284

### November 11, 2024

- [x] #285
- [x] #286
- [x] #287
- [x] #288

## November 13, 2024

- [x] #292
- [x] #300

## November 14, 2024

- [x] #306

## November 18, 2024

- [x] https://github.com/wazuh/wazuh-agent/issues/311

## November 19, 2024

- [x] https://github.com/wazuh/wazuh-agent/issues/314
- [x] https://github.com/wazuh/wazuh-agent/issues/315
- [x] https://github.com/wazuh/wazuh-agent/issues/316
- [x] https://github.com/wazuh/wazuh-agent/issues/317
- [x] https://github.com/wazuh/wazuh-agent/issues/318

## November 25, 2024

- [x] #345
- [x] #346
- [x] #347

## November 26, 2024

- [x] #354

## November 27, 2024

- [x] #358
- [x] #359 
- [x] #360

## November 28. 2024

- [x] #363
- [x] #365

## November 29, 2024

- [x] #366 
- [x] #367
- [x] #368 
- [x] #369 
- [x] #370

## December 2, 2024

- [x] #374

## December 3, 2024

- [x] #385

## December 5, 2024

- [x] #390
- [x] #394

## December 9, 2024

- [x] #404 
- [x] #405

## December 10, 2024

- [x] #411

## December 11, 2024

- [x] #413

## December 12, 2024

- [x] #416

## December 16, 2024

- [x] #430
- [x] #432

## December 17, 2024

- [x] #437

## December 18, 2024

- [x] https://github.com/wazuh/wazuh/issues/27341
