### ISSUE TITLE
Convert DBsync and Sysinfo from shared to static library

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-agent#251]
**Parent Issue:** https://github.com/wazuh/wazuh-agent/issues/241

## **Description**

The objective of this issue is to remove shared libraries from the Inventory module. Specifically, the DBsync and Sysinfo libraries should be converted from shared to static to improve compatibility across platforms.

## **Tasks**
- [ ] Convert the DBsync library from shared to static.
- [ ] Convert the Sysinfo library from shared to static.
- [ ] Validate Inventory functionality across the following platforms:
  - [ ] Linux
  - [ ] Windows
  - [ ] macOS
- [ ] Enable the Module Manager test for Windows, which previously failed due to missing DLL files.

## **Acceptance Criteria**
- DBsync and Sysinfo libraries are successfully converted to static libraries without impacting existing functionality.
- Inventory module passes functionality tests on Linux, Windows, and macOS platforms.
- Windows Module Manager tests run successfully without DLL or dependency errors.
- No shared library dependencies remain in the Inventory module after conversion.

**Comment by nbertoldo** [comment]
### Update 2024/10/25

- Converting _sysinfo_ and _dbsync_ from shared to static library.

**Comment by nbertoldo** [comment]
### Update 2024/10/30

When changing _sysinfo_ from `SHARED` to `STATIC` library I get these errors that occur at the time of linking _wazuh-agent_ executable:

```console
[ 95%] Linking CXX executable wazuh-agent
/usr/bin/ld: vcpkg_installed/x64-linux/debug/lib/librpm.a(rpmscript.o): in function `next_file':
/home/vagrant/wazuh-agent/src/vcpkg/buildtrees/librpm/x64-linux-dbg/lib/.././../src/9ed556c157-1b82a7a6d4.clean/lib/rpmscript.c:101:(.text+0x83): undefined reference to `lua_touserdata'
/usr/bin/ld: /home/vagrant/wazuh-agent/src/vcpkg/buildtrees/librpm/x64-linux-dbg/lib/.././../src/9ed556c157-1b82a7a6d4.clean/lib/rpmscript.c:102:(.text+0xad): undefined reference to `lua_pushstring'
...
```

It appears that librpm cannot find references to lua functions.
