### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-agent repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-agent#254]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-agent repository.

## Tasks

- [ ] Delete previous Alpha 2 release: https://github.com/wazuh/wazuh-agent/releases/tag/v4.10.0-alpha2.
- [ ] Delete previous v4.10.0-alpha2 tag.
- [ ] Ensure changelog is updated for 4.9.2 (if applicable).
- [ ] Bump revision for branch 4.9.2 on wazuh-agent repository.
- [ ] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-agent repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-agent/releases/tag/v4.9.2-rc1.
