### ISSUE TITLE
Support new stage Alpha 2 for 4.9.0 in wazuh-agent repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-agent#35]
## Description

This issue attempts to support a new stage Alpha 2 for 4.9.0 in the wazuh-agent repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-agent repository.
- [ ] Create tag v4.9.0-alpha2 from branch 4.9.0 on wazuh-agent repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-agent/releases/tag/v4.9.0-alpha2.
