### ISSUE TITLE
Develop OSLog Framework Integration

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-agent#467]
## Description

After completing the research on how to integrate the OSLog Framework into the new Wazuh Agent coded in C++, along with validating the configuration options, it is requested to develop this integration as a new Reader of the logcollector module.

### Tasks

1. **Extend Logcollector's `Setup` Function**
   - [x] Parse and validate the macOS-specific configuration options.
2. **Integrate OSLog API**
   - [x] Develop a wrapper to interact with the OSLog framework from C++.
   - [x] Ensure synchronous retrieval and filtering of logs based on queries, levels, and types.
   - [x] Develop this library as a standalone library that will be used by logcollector.
3. **Implement macOS Reader**
   - [x] Develop the Reader to process and transmit logs in the standard format.
   - [ ] Store the necessary information that will allow collection to resume in case the agent is restarted.
4. **Testing**
   - [x] Write unit tests and integration tests to validate the Reader's behavior with different queries, log levels, and types.
   - [x] Test the Reader's behavior with multiple configuration entries.
5. **Documentation**
   - [x] Prepare detailed documentation for the macOS Reader, including configuration examples, usage instructions, and limitations.

**Comment by jr0me** [comment]
## Update

Started writing a class in C++ to wrap around OSLogStore in a dedicated CMake target, to be used by the future ULS reader in Logcollector.

**Comment by jr0me** [comment]
## Update

Moving forward with the class:

This is a C++ wrapper around OSLogStore, handling Objective-C objects with memory management and providing an iterator-like interface for log entries. Including:
	•	A Pimpl idiom to hide Objective-C headers from the public C++ API.
	•	Iterator support, each with its own OSLogEnumerator retained/released correctly.

The wrapper is functional, iterates logs in C++ style, and respects Objective-C memory lifetimes. Next steps should be using this class from a log collector reader.

Wip commit for reference: https://github.com/wazuh/wazuh-agent/commit/aa0e41cd6ad5c22b7e14be2c23861b7b8693eb04

**Comment by jr0me** [comment]
## Update

Created support for log level querying and working towards type of log filtering.

**Comment by jr0me** [comment]
## Update

Revisited old implementation in `logcollector/macos_log.c` and reviewed macOS's "log" command (which is used by the former). There were some doubts about the types of logs and debug levels which are not explicitly documented on macOS SDK documentation site.

**Comment by jr0me** [comment]
## Update

- Converged timestamp parameters.
- Added missing log filter options (log type: trace, activity, log).
- Integrating with Logcollector
  - A problem surfaced that took some time to resolve; when the ULSReader was added as part of Logcollector, an increasing numbers of threads appeared all deadlocked in some apple logging stream service. After some time of debugging, the problem was found to be an undocumented behavior (probably a bug) of the Foundation sdk, see: https://openradar.appspot.com/FB12071731

**Comment by jr0me** [comment]
## Update

- Implemented reading macOS reader configuration from `wazuh-agent.yml`
- Developed an alternative to fetch all logs at once instead of iterating them but another strange behavior from OSLogStore appeared where a second ULSReader would seemingly block the first one, I could not find the source of the issue.

**Comment by jr0me** [comment]
## Update

Refactored the solution to retrieve all log entries at once, previous approach is still available in another branch.

Cleaned up git commit history and simplified the code.

Moved OSLogStoreWrapper within LogCollector project.

**Comment by jr0me** [comment]
## Update

- Wrote tests for `LogCollector:AddPlatformSpecificReaders` in OSX
- Wrote tests for `ULSReader`
- Some changes to enable testability of these classes.

**Comment by jr0me** [comment]
## Update

- Finished tests for OSLogStoreWrapper
- Reorganized file structure
- Ready for review
