### ISSUE TITLE
Modify Wazuh-Logcollector to send original EventChannel events

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-agent#50]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 5.0.0 | Logcollector | Agent | Packages/Sources | OS version |

### Description
The current implementation of Wazuh-Logcollector for EventChannel events wraps the original XML event inside a JSON object. This process alters the original event format, which is not ideal for the new implementation standards set by Wazuh-Engine, aiming to minimize manipulation or modification of logs at the agent level. This issue aims to modify the logcollector to send the original EventChannel event as is, without embedding it into a JSON structure.

### Objectives
- **Remove JSON Wrapping:** Modify logcollector to send the original XML event directly, without converting it into a JSON object with additional keys.
- **Deprecation of Message Key:** The `message` key that fetches event descriptions via the Windows API will be discontinued.

### Tasks
- [ ] **Update Logcollector Processing Logic:** Change the event processing in logcollector to bypass JSON object creation and send the original XML directly.
- [ ] **Adjust Output Formatting:** Ensure the logcollector outputs the XML in a format that is compatible with downstream processing by Wazuh-Engine.
- [ ] **Testing and Validation:** Thoroughly test the new implementation to ensure that EventChannel logs are collected and transmitted accurately.
- [ ] **Documentation Updates:** Update the Wazuh documentation to reflect these changes in logcollector behavior.

### Impact
This change will align Wazuh-Agent's logcollector with the new architectural requirements of Wazuh-Engine, ensuring that event logs are handled in their original format, thereby enhancing the integrity and reliability of log data.

**Comment by juliancnn** [comment]
Hi team,

This function:

https://github.com/wazuh/wazuh-agent/blob/2e26b62e463699c2b1dc6ed18e0a53778233f4c4/src/modules/logcollector/src/read_win_event_channel.c#L394-L522


It could look like this:

```c
void send_channel_event(EVT_HANDLE evt, os_channel *channel)
{
    DWORD buffer_length = 0;
    PEVT_VARIANT properties_values = NULL;
    DWORD count = 0;
    int result = 0;
    wchar_t *wprovider_name = NULL;
    char *provider_name = NULL;
    char *msg_from_prov = NULL;
    char *xml_event = NULL;
    char *beg_prov = NULL;
    char *end_prov = NULL;
    char *find_prov = NULL;
    size_t num;

    os_malloc(OS_MAXSTR, provider_name);

    result = EvtRender(NULL,
                       evt,
                       EvtRenderEventXml,
                       0,
                       NULL,
                       &buffer_length,
                       &count);
    if (result != FALSE || GetLastError() != ERROR_INSUFFICIENT_BUFFER) {
        merror(
            "Could not EvtRender() to determine buffer size for (%s) which returned (%lu)",
            channel->evt_log,
            GetLastError());
        goto cleanup;
    }

    if ((properties_values = malloc(buffer_length)) == NULL) {
        merror(
            "Could not malloc() memory to process event (%s) which returned [(%d)-(%s)]",
            channel->evt_log,
            errno,
            strerror(errno));
        goto cleanup;
    }

    if (!EvtRender(NULL,
                   evt,
                   EvtRenderEventXml,
                   buffer_length,
                   properties_values,
                   &buffer_length,
                   &count)) {
        merror(
            "Could not EvtRender() for (%s) which returned (%lu)",
            channel->evt_log,
            GetLastError());
        goto cleanup;
    }
    xml_event = convert_windows_string((LPCWSTR) properties_values);

    if (!xml_event) {
        goto cleanup;
    }

    find_prov = strstr(xml_event, "Provider Name=");

    if(find_prov){
        beg_prov = strchr(find_prov, '\'');
        if(beg_prov){
            end_prov = strchr(beg_prov+1, '\'');

            if (end_prov){
                num = end_prov - beg_prov - 1;

                if(num > OS_MAXSTR - 1){
                    mwarn("The event message has exceeded the maximum size.");
                    goto cleanup;
                }

                memcpy(provider_name, beg_prov+1, num);
                provider_name[num] = '\0';
                find_prov = '\0';
                beg_prov = '\0';
                end_prov = '\0';
            }
        }
    }

     if (provider_name) {
        wprovider_name = convert_unix_string(provider_name);

        if (wprovider_name && (msg_from_prov = get_message(evt, wprovider_name, EvtFormatMessageEvent)) == NULL) {
            merror(
                "Could not get message for (%s)",
                channel->evt_log);
        }
    }

    win_format_event_string(xml_event);

    w_logcollector_state_update_file(channel->evt_log, strlen(xml_event));

    if (SendMSG(logr_queue, xml_event, "EventChannel", WIN_EVT_MQ) < 0) {
        merror(QUEUE_SEND);
        w_logcollector_state_update_target(channel->evt_log, "agent", true);
    } else {
        w_logcollector_state_update_target(channel->evt_log, "agent", false);
    }

    if (channel->bookmark_enabled) {
        update_bookmark(evt, channel);
    }

cleanup:
    os_free(msg_from_prov);
    os_free(xml_event);
    os_free(properties_values);
    os_free(provider_name);
    os_free(wprovider_name);

    return;
}
```


Regards,

**Comment by vikman90** [comment]
Thank you, @juliancnn.

Therefore, we need to port the Logcollector changes at https://github.com/wazuh/wazuh/pull/17880.

**Comment by vikman90** [comment]
## Update

Today, I created a new branch with the ported commit from Logcollector to the Engine branch, ensuring that the original XML events are sent directly without JSON wrapping. 

Additionally, I drafted a pull request detailing the modifications and the objectives of the update, aligning with the new standards set by Wazuh-Engine:

- https://github.com/wazuh/wazuh-agent/pull/61
