### ISSUE TITLE
Support new stage RC 1 for 4.8.2 in wazuh-agent repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-agent#90]
## Description

This issue attempts to support a new stage RC 1 for 4.8.2 in the wazuh-agent repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.2 (if applicable).
- [ ] Bump revision for branch 4.8.2 on wazuh-agent repository.
- [ ] Create tag v4.8.2-rc1 from branch 4.8.2 on wazuh-agent repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-agent/releases/tag/v4.8.2-rc1.
